In [433]:
#Assignment-3
#NumPy



In [434]:
import numpy as np

In [435]:
import pandas as pd

In [436]:
#Q1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.
arr=np.arange(0,6)
print("array:",arr)
print("data type:", arr.dtype)


array: [0 1 2 3 4 5]
data type: int64


In [437]:
#Q2. Given a NumPy array 'arr', check if its data type is float64.
arr = np.array([1.5, 2.6, 3.7])
print("data type:",arr.dtype)

data type: float64


In [438]:
#Q3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.
arr=np.array([3+6j,4+8j,5+9j])
print("data type:",arr.dtype)


data type: complex128


In [439]:
#Q4. Convert an existing NumPy array 'arr' of integers to float32 data type.
arr=np.array([1,2,3,4,5.1])
print("data type:",arr.astype(np.float32).dtype)



data type: float32


In [440]:
#Q5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.
arr=np.arange(0.1,6.0)
print("data type:",arr.astype(np.float32).dtype)

data type: float32


In [441]:
#Q6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type.
def array_attributes():
    arr=np.array(np.arange(10))
    print("shape:",arr.shape)
    print("size:",arr.size)
    print("data type:",arr.dtype)
array_attributes()   





shape: (10,)
size: 10
data type: int64


In [442]:
#Q7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.
def array_dimension():
    arr=np.array([[1,2,3,4],[5,6,7,8]])
    print("dimension:",arr.ndim)
array_dimension()    

dimension: 2


In [443]:
#Q8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes.
def item_size_info():
    arr=np.array(np.arange(10))
    print("item_size",arr.itemsize)
    print("total_size",arr.nbytes)
item_size_info()    


item_size 8
total_size 80


In [444]:
#Q9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.
def array_stride():
    arr=np.array(np.arange(10))
    print("strides:",arr.strides)
array_stride() 

strides: (8,)


In [445]:
#Q10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array
def shape_stride_relationship():
    arr=np.array(np.arange(10))
    print("shape:",arr.shape)
    print("strides:",arr.strides)
shape_stride_relationship()    



shape: (10,)
strides: (8,)


In [446]:
#Q11. Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of zeros with `n` elements.
def create_zeros_array(n):
    arr=np.zeros(n)
    return arr
create_zeros_array(6)

array([0., 0., 0., 0., 0., 0.])

In [447]:
#Q12. Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D NumPy array filled with ones of size `rows x cols`.
def create_ones_matrix():
    arr=np.ones((3,4))
    return arr
create_ones_matrix()


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [448]:
#Q13. Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified `step`.
def generate_range_array(start,stop,step):
    arr=np.arange(start,stop,step)
    return arr
generate_range_array(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [449]:
#Q14. Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as arguments and generates a NumPy array with num equally spaced values between `start` and `stop` (inclusive).
def generate_linear_space(start,stop,num):
    arr=np.linspace(start,stop,num)
    return arr
generate_linear_space(1.0,15.5,15)


array([ 1.        ,  2.03571429,  3.07142857,  4.10714286,  5.14285714,
        6.17857143,  7.21428571,  8.25      ,  9.28571429, 10.32142857,
       11.35714286, 12.39285714, 13.42857143, 14.46428571, 15.5       ])

In [450]:
#Q15. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square identity matrix of size `n x n` using `numpy.eye`.
def create_identity_matrix(n):
    arr=np.eye(n)
    return arr
create_identity_matrix(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [451]:
#Q16. Write a function that takes a Python list and converts it into a NumPy array.
def list_to_array(l):
    arr=np.array(l)
    return arr
list_to_array([1,2,3,4,7,8,9,19])

array([ 1,  2,  3,  4,  7,  8,  9, 19])

In [452]:
#Q17. Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the same data.
arr=np.arange(10)
a=arr.view()
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [453]:
#Q18. Write a function that takes two NumPy arrays and concatenates them along a specified axis. 
def concatenate_two_arrays(axis):
    arr1=np.random.rand(10) 
    arr2=np.random.rand(10) 
    print("concatenation of two array:",np.concatenate((arr1, arr2),axis=axis))
concatenate_two_arrays(0)

concatenation of two array: [0.10248345 0.12107632 0.57907873 0.65199579 0.20918154 0.1284689
 0.24088418 0.80267945 0.91815678 0.49775398 0.81466299 0.39486712
 0.86136568 0.11877056 0.35455551 0.7792446  0.31128371 0.18509957
 0.52292128 0.03221754]


In [454]:
#Q19. Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.concatenate`
array1=np.random.rand(2,3)
array2=np.random.rand(2,2)
concatenated_array=np.concatenate((array1,array2),axis=1)
print("Concatenated Array:\n",concatenated_array)
 

Concatenated Array:
 [[0.32461634 0.32243161 0.09880756 0.87809212 0.00480937]
 [0.80522823 0.81550786 0.984226   0.81683924 0.63742788]]


In [455]:
#Q20. Write a function that vertically stacks multiple NumPy arrays given as a list.

def vertical_stack():
    arr1=np.array([[1,2],[3,4]])
    arr2=np.array([[5,6],[7,8]])
    arr3=np.array([[8,9],[3,4]])
    stacked=np.vstack((arr1,arr2,arr3))
    return stacked
vertical_stack()

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8],
       [8, 9],
       [3, 4]])

In [456]:
#Q21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size.
def array_of_integers(start,stop,step):
    arr=np.arange(start,stop+1,step)
    return arr
array_of_integers(1,25,3)



array([ 1,  4,  7, 10, 13, 16, 19, 22, 25])

In [457]:
#Q22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).
def array_of_10():
    arr=np.linspace(0, 1, 10)
    return arr
array_of_10()



array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [458]:
#Q23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).
def array_of_5():
    arr=np.logspace(1,3,5)
    return arr
array_of_5()

array([  10.        ,   31.6227766 ,  100.        ,  316.22776602,
       1000.        ])

In [459]:
#Q24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100.
arr=np.random.randint(1,101,size=(5,3)) 
df=pd.DataFrame(arr) 
print(df)


    0    1   2
0   1   31  22
1  78  100  80
2  85   51  60
3  57   90  25
4  52    7  28


In [460]:
#Q25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. Use NumPy operations within the Pandas DataFrame
arr=np.random.randn(1,10) 
df=pd.DataFrame(arr)
def replace_negative_with_zero(df):
    df[df<0]=0
    return df
df=replace_negative_with_zero(df)
print(df)


     0         1    2    3    4    5    6    7         8    9
0  0.0  1.139873  0.0  0.0  0.0  0.0  0.0  0.0  0.219515  0.0


In [461]:
#Q26. Access the 3rd element from the given NumPy array.
arr = np.array([10, 20, 30, 40, 50])
print(arr[3])

40


In [462]:
#Q27. Retrieve the element at index (1, 2) from the 2D NumPy array.
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print(arr_2d[1,2])

6


In [463]:
#Q28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.
arr = np.array([3, 8, 2, 10, 5, 7])
elements_greater_than_5=arr[arr>5]
print(elements_greater_than_5)



[ 8 10  7]


In [464]:
#Q29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
sliced_array=arr[2:6]
print(sliced_array)

[3 4 5 6]


In [465]:
#Q30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
sub_array=arr_2d[0:2, 1:3] 
print(sub_array)


[[2 3]
 [5 6]]


In [466]:
#Q31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array.
def extract_elements(arr,indices):
    return arr[indices[:,0],indices[:,1]]
arr_2d=np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
indices=np.array([[0,1], 
                    [2,0],  
                    [1,2]]) 
print(extract_elements(arr_2d,indices))





[2 7 6]


In [467]:
#Q32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.
def filter_greater_than(arr,threshold):
    return arr[arr>threshold]
arr=np.array([3, 8, 2, 10, 5, 7])
threshold=5
print(filter_greater_than(arr,threshold))



[ 8 10  7]


In [468]:
#Q33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension.
def extract_elements(arr,idx0,idx1,idx2):
    return arr[idx0,idx1,idx2]
arr_3d=np.array([[[ 1, 2, 3],
                    [ 4, 5, 6],
                    [ 7, 8, 9]],
                   [[10,11,12],
                    [13,14,15],
                    [16,17,18]],
                   [[19,20,21],
                    [22,23,24],
                    [25,26,27]]])
idx0=np.array([0, 1, 2])
idx1=np.array([1, 2, 0])
idx2=np.array([2, 0, 1])
print(extract_elements(arr_3d,idx0,idx1,idx2))



[ 6 16 20]


In [469]:
#Q34. Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.
def elements_satisfying_conditions(arr,cond1,cond2):
    result=arr[cond1&cond2]
    return result
arr=np.array([1,2,3,4,5,6,7,8,9,10])
cond1=(arr>4) 
cond2=(arr%2==0) 
result=elements_satisfying_conditions(arr,cond1,cond2)
print(result)



[ 6  8 10]


In [470]:
#Q35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.
def extract_elements(arr,row_indices,col_indices):
    return arr[row_indices,col_indices]
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
row_indices=np.array([0,1,2])
col_indices=np.array([2,0,1])
print(extract_elements(arr,row_indices,col_indices))


[3 4 8]


In [471]:
#Q36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr + 5)

[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [472]:
#Q37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arr1 using NumPy broadcasting.
arr1=np.array([1,2,3])  
arr2=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]]) 
result=arr2*arr1[:,np.newaxis]
print(result)


[[ 1  2  3  4]
 [10 12 14 16]
 [27 30 33 36]]


In [473]:
#Q38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.
arr1=np.array([1,2,3,4])
arr2=np.array([[10,20,30],
                [40,50,60],
                [70,80,90],
                [100,110,120]])
result=arr2+arr1[:,np.newaxis]
print(result)




[[ 11  21  31]
 [ 42  52  62]
 [ 73  83  93]
 [104 114 124]]


In [474]:
#Q39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.
arr1=np.array([[1],[2],[3]]) 
arr2=np.array([[4,5,6]]) 
print(arr1+arr2)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [475]:
#Q40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. Handle the shape incompatibility.
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[7,8],[9,10]])
print(arr1*arr2[:,:,np.newaxis])

[[[ 7 14 21]
  [32 40 48]]

 [[ 9 18 27]
  [40 50 60]]]


In [476]:
#Q41. Calculate column wise mean for the given array:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np.mean(arr,axis=0))

[2.5 3.5 4.5]


In [477]:
#Q42. Find maximum value in each row of the given array:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np.max(arr,axis=1))

[3 6]


In [478]:
#Q43. For the given array, find indices of maximum value in each column.
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np.argmax(arr,axis=0))


[1 1 1]


In [479]:
#Q44. For the given array, apply custom function to calculate moving sum along rows.
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np.cumsum(arr,axis=1))

[[ 1  3  6]
 [ 4  9 15]]


In [480]:
#Q45. In the given array, check if all elements in each column are even.
arr = np.array([[2, 4, 6], [3, 5, 7]])
print(np.all(arr%2==0,axis=0))

[False False False]


In [481]:
#Q46. Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the reshaped matrix.
original_array = np.array([1, 2, 3, 4, 5, 6])
def reshape_array(arr,m,n):
    return arr.reshape(m,n)
print(reshape_array(original_array,2,3))



[[1 2 3]
 [4 5 6]]


In [482]:
#Q47. Create a function that takes a matrix as input and returns the flattened array.
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
def flatten_matrix(matrix):
    return matrix.flatten()
print(flatten_matrix(input_matrix))



[1 2 3 4 5 6]


In [483]:
#Q48. Write a function that concatenates two given arrays along a specified axis.
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
def concat_arrays(arr1,arr2,axis=0):
    return np.concatenate((arr1, arr2),axis=axis)
concat_result_rows=concat_arrays(array1,array2,axis=0)
print("rows:",concat_result_rows)
concat_result_cols=concat_arrays(array1,array2,axis=1)
print("columns:",concat_result_cols)



rows: [[1 2]
 [3 4]
 [5 6]
 [7 8]]
columns: [[1 2 5 6]
 [3 4 7 8]]


In [484]:
#Q49. Create a function that splits an array into multiple sub-arrays along a specified axis.
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
def easy_split_array(arr,num_splits,axis=0):
    return np.array_split(arr, num_splits,axis=axis)
split_rows=easy_split_array(original_array,3,axis=0)
print("Splited rows:", split_rows)
split_cols=easy_split_array(original_array,3,axis=1)
print("Splited columns:",split_cols)






Splited rows: [array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]
Splited columns: [array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


In [485]:
#Q50. Write a function that inserts and then deletes elements from a given array at specified indices.
original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

def modify_array(arr,indices_to_insert,values_to_insert,indices_to_delete):
    arr=np.insert(arr,indices_to_insert, values_to_insert)
    arr=np.delete(arr,indices_to_delete)
    return arr
print(modify_array(original_array,indices_to_insert,values_to_insert,indices_to_delete))








[ 1 10  4 11  5]


In [486]:
#Q51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10. Perform element-wise addition between `arr1` and `arr2`.
arr1=np.random.randint(1,100,size=10)
arr2=np.arange(1,11)
add=arr1+arr2
print("arr1:",arr1)
print("arr2:",arr2)
print("addition of 2 arrays:",add)


arr1: [21 82 20 62 92 69 38 58 36 61]
arr2: [ 1  2  3  4  5  6  7  8  9 10]
addition of 2 arrays: [22 84 23 66 97 75 45 66 45 71]


In [487]:
#Q52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers from 1 to 10. Subtract `arr2` from `arr1` element-wise.
arr1=np.arange(10, 0, -1)
arr2=np.arange(1, 11)
sub=arr1-arr2
print(sub)


[ 9  7  5  3  1 -1 -3 -5 -7 -9]


In [488]:
#Q53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5. Perform element-wise multiplication between `arr1` and `arr2`.
arr1=np.random.randint(1,10,size=5)
arr2=np.arange(1,6)
mul=arr1*arr2
print("arr1:",arr1)
print("arr2",arr2)
print("multiplication of arrays:",mul)

arr1: [9 9 2 9 8]
arr2 [1 2 3 4 5]
multiplication of arrays: [ 9 18  6 36 40]


In [489]:
#Q54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1 to 5. Perform element-wise division of `arr1` by `arr2`.
arr1=np.arange(2,11,2)
arr2=np.arange(1,6)
div=arr1/arr2
print(div)





[2. 2. 2. 2. 2.]


In [490]:
#Q55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.
arr1=np.arange(1,6)
arr2=arr1[::-1]
result=np.power(arr1,arr2)
print(result)


[ 1 16 27 16  5]


In [491]:
#Q56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
def count_substring(arr,substring):
    count=0
    for i in arr:
        count+=i.count(substring)
    return count
substring='hello'
result=count_substring(arr,substring)
print(result)


3


In [492]:
#Q57. Write a function that extracts uppercase characters from a NumPy array of strings.
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
def extract_uppercase(arr):
    return np.array([''.join([char for char in string if char.isupper()]) for string in arr])
print(extract_uppercase(arr))




['H' 'W' 'OAI' 'GPT']


In [493]:
#Q58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
def replace_substring(arr,old_substring,new_substring):
    return np.char.replace(arr,old_substring,new_substring)
new_arr=replace_substring(arr,'apple','fruit')
print(new_arr)



['fruit' 'banana' 'grape' 'pinefruit']


In [494]:
#Q59. Write a function that concatenates strings in a NumPy array element-wise.
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])
def concatenate_arrays(arr1,arr2):
    return arr1+arr2
print(concatenate_arrays(arr1,arr2))



['HelloOpen' 'WorldAI']


In [495]:
#Q60. Write a function that finds the length of the longest string in a NumPy array.
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
def length_of_longest_string(arr):
    length=0
    for i in arr:
        if len(i)>length:
            length=len(i)
    return length
print("Length of the longest string:",length_of_longest_string(arr))
      

Length of the longest string: 9


In [496]:
#Q61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and standard deviation of the dataset using NumPy's functions.
dataset=np.random.randint(1,1001,size=100)
print("mean:",np.mean(dataset))
print("median:",np.median(dataset))
print("variance",np.var(dataset))
print("standard deviation :",np.std(dataset))

mean: 534.31
median: 552.0
variance 93132.13390000003
standard deviation : 305.1755788066929


In [497]:
#Q62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.
arr=np.random.randint(1,100,size=50)
percentiles=np.percentile(arr,[25,75])
print("25th percentile:",percentiles[0])
print("75th percentile:",percentiles[1])

25th percentile: 24.5
75th percentile: 75.0


In [498]:
#Q63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's `corrcoef` function.
arr1=np.array([1,2,3,4,5])
arr2=np.array([10, 20, 30, 40, 50])
correlation_matrix=np.corrcoef(arr1,arr2)
print(correlation_matrix)


[[1. 1.]
 [1. 1.]]


In [499]:
#Q64. Create two matrices and perform matrix multiplication using NumPy's `dot` function.
C=np.matrix([[1,2],[3,4],[5,6]])
D=np.matrix([[7,8,9,10],[11,12,13,14]])
multiplication=np.dot(C,D)
print(multiplication)

[[ 29  32  35  38]
 [ 65  72  79  86]
 [101 112 123 134]]


In [500]:
#Q65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles.
arr=np.random.randint(10,1001,size=50)
percentiles=np.percentile(arr,[10,50,90,25,75])
print("10th percentile:",percentiles[0])
print("50th percentile (median):",percentiles[1])
print("90th percentile:",percentiles[2])
print("1st quartile (25th percentile):",percentiles[3])
print("3rd quartile (75th percentile):",percentiles[4])

arr

10th percentile: 75.7
50th percentile (median): 509.0
90th percentile: 890.7
1st quartile (25th percentile): 164.75
3rd quartile (75th percentile): 824.25


array([852, 943, 279, 143, 608, 213, 196, 111, 977, 537,  87, 185, 131,
       237, 531,  78, 681,  90, 723, 849, 154, 971, 723,  11, 792, 942,
       337,  55, 840,  15, 719,  51, 493,  36, 834, 338, 798, 402, 464,
       957, 885, 878, 738, 858, 833, 525, 262, 736, 277, 158], dtype=int32)

In [501]:
#Q66. Create a NumPy array of integers and find the index of a specific element.
arr=np.array([10,20,30,40,50])
index=np.where(arr==30)[0][0]
print("Index of 30:",index)



Index of 30: 2


In [502]:
#Q67. Generate a random NumPy array and sort it in ascending order.
arr=np.random.randint(1,50,size=10)
print("array:",arr)
print("sorted array",np.sort(arr))






array: [20 34 22 36  3 11 49 10 27 35]
sorted array [ 3 10 11 20 22 27 34 35 36 49]


In [503]:
#Q68. Filter elements >20  in the given NumPy array.
arr = np.array([12, 25, 6, 42, 8, 30])
filtered_arr=arr[(arr>20)]
print(filtered_arr)

[25 42 30]


In [504]:
#Q69. Filter elements which are divisible by 3 from a given NumPy array.
arr = np.array([1, 5, 8, 12, 15])
filtered_arr=arr[arr%3==0]
print(filtered_arr)


[12 15]


In [505]:
#Q70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.
arr = np.array([10, 20, 30, 40, 50])
filtered_arr=arr[(arr>=20)&(arr<=40)]
print(filtered_arr)


[20 30 40]


In [506]:
#Q71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder.
arr = np.array([1, 2, 3])
byte_order=arr.dtype.byteorder
print("byte_order:",byte_order)

byte_order: =


In [507]:
#Q72. For the given NumPy array, perform byte swapping in place using `byteswap()`.
arr = np.array([1, 2, 3], dtype=np.int32)
arr.byteswap(inplace=True)
print("Byte-swapped array:",arr)


Byte-swapped array: [16777216 33554432 50331648]


In [508]:
#Q73. For the given NumPy array, swap its byte order without modifying the original array using `newbyteorder()`.
arr = np.array([1, 2, 3],dtype=np.int32)
byte_swapped_arr = arr.view(arr.dtype.newbyteorder())
print("Original array:", arr)
print("Byte-swapped array:", byte_swapped_arr)


Original array: [1 2 3]
Byte-swapped array: [16777216 33554432 50331648]


In [509]:
#Q74. For the given NumPy array and swap its byte order conditionally based on system endianness using `newbyteorder()`.
arr=np.array([1, 2, 3],dtype=np.int32)
new_arr=arr.view(arr.dtype.newbyteorder())
print("Original array:",arr)
print("Byte-swapped array:",new_arr)


Original array: [1 2 3]
Byte-swapped array: [16777216 33554432 50331648]


In [510]:
#Q75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` attribute `byteorder`.
arr=np.array([1, 2, 3],dtype=np.int32)
print("Byte order:",arr.dtype.byteorder)
#If the byte order is =,it means no byte swapping is necessary.


Byte order: =


In [511]:
#Q76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.
arr1=np.arange(1,11)
print("original array",arr1)
copy_arr=arr1.copy()
copy_arr[3]=9
print("copy of array after modification:",copy_arr)
#it doesnt affect the original array
print("original array after modification:",arr1)

original array [ 1  2  3  4  5  6  7  8  9 10]
copy of array after modification: [ 1  2  3  9  5  6  7  8  9 10]
original array after modification: [ 1  2  3  4  5  6  7  8  9 10]


In [512]:
#Q77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.
matrix=np.random.randint(1,11,size=(3, 3))
print("original matrix:",matrix)
view_slice=matrix[:,2]
print("sliced view_slice",view_slice)
view_slice[1]=5
print("modified view_slice",view_slice)
#it modifies the original matrix also
print("original matrix after modification:",matrix)

original matrix: [[3 9 1]
 [5 6 5]
 [1 8 7]]
sliced view_slice [1 5 7]
modified view_slice [1 5 7]
original matrix after modification: [[3 9 1]
 [5 6 5]
 [1 8 7]]


In [513]:
#Q78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice `view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.
array_a=np.arange(1, 13).reshape(4, 3)
print("original array:",array_a)
view_b = array_a[:,1]  
print("Sliced view_b:",view_b)
view_b+= 5
print("Updated  array after addition of 5:",view_b)
#it modifies the original array
print("Original array after alteration:",array_a)


original array: [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Sliced view_b: [ 2  5  8 11]
Updated  array after addition of 5: [ 7 10 13 16]
Original array after alteration: [[ 1  7  3]
 [ 4 10  6]
 [ 7 13  9]
 [10 16 12]]


In [514]:
#Q79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view `reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it reflects changes in the original `orig_array`.
orig_array=np.random.randint(1,8,size=(2, 4))
print("original array:",orig_array)
reshaped_view=orig_array.reshape(4,2)
print("reshaped array:",reshaped_view)
reshaped_view[1]=5
print("modified reshaped array:",reshaped_view)
#the changes is reflected in original array
print("original array after changes:",orig_array)


original array: [[3 6 1 4]
 [4 2 6 6]]
reshaped array: [[3 6]
 [1 4]
 [4 2]
 [6 6]]
modified reshaped array: [[3 6]
 [5 5]
 [4 2]
 [6 6]]
original array after changes: [[3 6 5 5]
 [4 2 6 6]]


In [515]:
#Q80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.
data=np.random.randint(1,11,size=(3, 4))
print(data)
data_copy=data[data>5].copy()
print("copy of data >5:",data_copy)
data_copy[1]=500
print("modified  data_copy:",data_copy)
#it doesnt affect the value of original data
print("original data after modification:",data)



[[7 3 7 5]
 [6 9 5 5]
 [7 9 2 7]]
copy of data >5: [7 7 6 9 7 9 7]
modified  data_copy: [  7 500   6   9   7   9   7]
original data after modification: [[7 3 7 5]
 [6 9 5 5]
 [7 9 2 7]]


In [516]:
#Q81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them.
A=np.matrix([[1,2,3],
            [4,5,6],
            [7,8,9]])
B=np.matrix([[5,6,7],
           [8,9,1],
           [3,4,2]])
add=A+B
sub=A-B
print(add)
print(sub)


[[ 6  8 10]
 [12 14  7]
 [10 12 11]]
[[-4 -4 -4]
 [-4 -4  5]
 [ 4  4  7]]


In [517]:
#Q82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.
C=np.matrix([[1,2],[3,4],[5,6]])
D=np.matrix([[7,8,9,10],[11,12,13,14]])
mul=C@D
print(mul)
#or
multi=np.dot(C,D)
print(multi)

[[ 29  32  35  38]
 [ 65  72  79  86]
 [101 112 123 134]]
[[ 29  32  35  38]
 [ 65  72  79  86]
 [101 112 123 134]]


In [518]:
#Q83. Create a matrix `E` and find its transpose.
E=np.matrix([[1,2,3],
            [4,5,6],
            [7,8,9]])
transpose=(E.T)
print(transpose)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [519]:
#Q84. Generate a square matrix `F` and compute its determinant.
F=np.matrix([[5,6,7],
           [8,9,1],
           [3,4,2]])
F_determinant=np.linalg.det(F)
print("determinant of F:",F_determinant)

determinant of F: 27.0


In [520]:
#Q85. Create a square matrix `G` and find its inverse.
G=np.matrix([[4, 7, 2],
            [3, 6, 1],
            [2, 5, 3]])
G_inverse=np.linalg.inv(G)
print("Inverse of G:")
print(G_inverse)


Inverse of G:
[[ 1.44444444 -1.22222222 -0.55555556]
 [-0.77777778  0.88888889  0.22222222]
 [ 0.33333333 -0.66666667  0.33333333]]
